### ISSUE TITLE
Error in svd(x, nu = 0) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by IsmailM** [GeoDiver/RCore#104]
Affects 10 Geo Datasets

e.g.

```
Running: Rscript 'R-Core/overview.R' --dbrdata analysis/GDS1332/GDS1332.RData --rundir 'analysis/GDS1332/overview/' --analyse 'Boxplot,PCA' --accession GDS1332 --factor 'disease.state' --popA 'normal' --popB 'presymptomatic,symptomatic' --popname1 'Group1' --popname2 'Group2' --dev TRUE


[1] "Overview: GeoDiver is starting"
[1] "Overview: Libraries have been loaded"
[1] "Overview: Data Preprocessed!"
[1] "Overview: Factors and Populations have been set"
[1] "Overview: Boxplot has been produced"
Warning message:
Removed 1313 rows containing non-finite values (stat_boxplot). 
Error in svd(x, nu = 0) : infinite or missing values in 'x'
Calls: prcomp -> prcomp.default -> svd
Execution halted
```

[svd-error.txt](https://github.com/SBCS-Bioinformatics/R-Core/files/154471/svd-error.txt)

**Comment by IsmailM** [comment]
Update: This is now affecting 78 Geo datasets

[svd-error.txt](https://github.com/SBCS-Bioinformatics/R-Core/files/204913/infinite.or.missing.values.in.x.txt)

**Comment by IsmailM** [comment]
Update?

**Comment by sureshhewabi** [comment]
My openion is this should be an old error. Did we re-run this after we implement imputation and other stuff? I suggest to look into this matter after we run everything with our bug fixes. Any better suggestions?

**Comment by IsmailM** [comment]
Agreed. 

Let's take another look at this once we've added all other functionality. We could even look at this while the paper has been submitted.

**Comment by sureshhewabi** [comment]
I am quite sure that this error is directly related with #110 issue. because if we have 0.000 values for the entire row, then it cannot compute svd. We can test this after fixing #110

**Comment by IsmailM** [comment]
Closing this for now - Will reopen if neccessary
